repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
        -   id: trailing-whitespace
            types: [python]
        -   id: end-of-file-fixer
            types: [python]
        -   id: check-yaml
        -   id: check-added-large-files
  -   repo: local
      hooks:
        -   id: mypy
            name: mypy
            entry: mypy
            language: system
            types: [python]
        -   id: pylint
            name: pylint
            entry: pylint
            language: system
            types: [python]
