- public_root: data/root
- peers:
    - id: endorser1
      type: endorser
      root: data/endorser1
      bind_addr: [ 127.0.0.1, 16845 ]
      public_addr: [ 127.0.0.1, 16845 ]
      connections: [ endorser2 ]
    - id: endorser2
      type: endorser
      root: data/endorser2
      bind_addr: [ 127.0.0.1, 16846 ]
      public_addr: [ 127.0.0.1, 16846 ]
      connections: [ order1 ]
    - id: endorser3
      type: endorser
      root: data/endorser3
      bind_addr: [ 127.0.0.1, 16847 ]
      public_addr: [ 127.0.0.1, 16847 ]
      connections: [ order2 ]
    - id: orderer1
      type: orderer
      root: data/orderer1
      bind_addr: [ 127.0.0.1, 16848 ]
      public_addr: [ 127.0.0.1, 16848 ]
      connections: [ order2 ]
    - id: orderer2
      type: orderer
      root: data/orderer2
      bind_addr: [ 127.0.0.1, 16849 ]
      public_addr: [ 127.0.0.1, 16849 ]
      connections: [ order3 ]
    - id: orderer3
      type: orderer
      root: data/orderer3
      bind_addr: [ 127.0.0.1, 16850 ]
      public_addr: [ 127.0.0.1, 16850 ]
      connections: [ order4 ]
    - id: orderer4
      type: orderer
      root: data/orderer4
      bind_addr: [ 127.0.0.1, 16851 ]
      public_addr: [ 127.0.0.1, 16851 ]
      connections: [ order1, endorser1 ]
- clients:
    - id: client1
      type: admin
      root: data/client1
    - id: client2
      type: account
      root: data/client2
    - id: client3
      type: account
      root: data/client3
    - id: client4
      type: account
      root: data/client4
