public_root: data/root
peers:
  - id: orderer
    type: orderer
    root: data/orderer
    bind_addr: [ 127.0.0.1, 16848 ]
    public_addr: [ 127.0.0.1, 16848 ]
  - id: endorser1
    type: endorser
    root: data/endorser1
    bind_addr: [ 127.0.0.1, 16845 ]
    public_addr: [ 127.0.0.1, 16845 ]
  - id: endorser2
    type: endorser
    root: data/endorser2
    bind_addr: [ 127.0.0.1, 16846 ]
    public_addr: [ 127.0.0.1, 16846 ]
  - id: endorser3
    type: endorser
    root: data/endorser3
    bind_addr: [ 127.0.0.1, 16847 ]
    public_addr: [ 127.0.0.1, 16847 ]
clients:
  - id: client1
    type: admin
    root: data/client1
    port: 16489
  - id: client2
    type: client
    root: data/client2
    port: 16490
  - id: client3
    type: client
    root: data/client3
    port: 16491
  - id: client4
    type: client
    root: data/client4
    port: 16492
web:
  static_root: frontend/dist
